/**
 * Counter (POS) inputs — sessions, sales, held sales (Day 18). Shared: the Day-19 sale screen
 * validates its cart with the same schemas the server applies.
 *
 * A counter sale sends **quantities, never totals**. Prices are resolved server-side by the
 * pricing engine on every sale; a client-supplied unit price is honoured only for a user holding
 * `order:priceOverride`, and a discount only for one holding `pos:discount`.
 */

import { z } from 'zod';

import { MFS_PROVIDERS, RETURN_REASONS } from './enums.js';

const objectId = z.string().regex(/^[0-9a-fA-F]{24}$/, 'Must be a valid id');
const minor = z.number().int().min(0).max(Number.MAX_SAFE_INTEGER);

/** Bangladesh notes and coins, in taka — the cash-count grid on the close-shift screen. */
export const DENOMINATIONS = [1000, 500, 200, 100, 50, 20, 10, 5, 2, 1] as const;

// ─── Sessions ───────────────────────────────────────────────────────────────────────────

export const openSessionSchema = z
  .object({
    locationId: objectId,
    /** Which till, when a counter has more than one. */
    terminalCode: z.string().trim().toUpperCase().min(1).max(10).default('T1'),
    /** Cash in the drawer at the start of the shift. */
    openingFloatMinor: minor,
  })
  .strict();

export const closeSessionSchema = z
  .object({
    /** The cash count, note by note. Counted cash is computed from it — never typed as a total. */
    denominations: z
      .array(
        z
          .object({
            note: z.number().int().positive(),
            count: z.number().int().min(0).max(100_000),
          })
          .strict(),
      )
      .max(20),
    note: z.string().trim().max(300).nullable().optional(),
  })
  .strict();

export type OpenSessionInput = z.infer<typeof openSessionSchema>;
export type CloseSessionInput = z.infer<typeof closeSessionSchema>;

// ─── Sale ───────────────────────────────────────────────────────────────────────────────

export const saleLineSchema = z
  .object({
    productId: objectId,
    variantId: objectId.nullable().optional(),
    uomCode: z.string().trim().toUpperCase().max(10).nullable().optional(),
    qty: z.number().int('Whole units only').min(1, 'At least 1').max(100_000),
    serials: z.array(z.string().trim().toUpperCase().min(1).max(60)).max(1000).optional(),
    lotNo: z.string().trim().toUpperCase().max(40).nullable().optional(),
    /** A price other than the resolved one. Needs `order:priceOverride`. */
    unitPriceMinor: minor.optional(),
    /** A discount on this line, minor units. Needs `pos:discount`. */
    lineDiscountMinor: minor.optional(),
  })
  .strict();

/**
 * `EXCHANGE` spends the credit of a counter return settled as an exchange (Day 20): the customer
 * brought something back and takes something else. It is exact like card — it gives no change.
 */
export const POS_TENDERS = ['CASH', 'CARD', 'MFS', 'BANK', 'CHEQUE', 'EXCHANGE'] as const;
export type PosTender = (typeof POS_TENDERS)[number];

export const tenderSchema = z
  .object({
    method: z.enum(POS_TENDERS),
    /** What the customer handed over in this method. Cash may exceed the total; change is given. */
    amountMinor: minor.refine((v) => v > 0, 'Must be more than zero'),
    mfs: z
      .object({
        provider: z.enum(MFS_PROVIDERS),
        trxId: z.string().trim().min(4).max(40),
        senderNumber: z.string().trim().max(20).nullable().optional(),
      })
      .strict()
      .optional(),
    cheque: z
      .object({
        chequeNo: z.string().trim().min(1).max(30),
        bankName: z.string().trim().max(80).nullable().optional(),
        chequeDate: z.string().date().nullable().optional(),
      })
      .strict()
      .optional(),
    /** Card slip or bank transfer reference. */
    reference: z.string().trim().max(60).nullable().optional(),
    /** For `EXCHANGE`: the return whose credit this spends. */
    returnId: objectId.optional(),
  })
  .strict()
  .superRefine((t, ctx) => {
    if (t.method === 'EXCHANGE' && !t.returnId)
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['returnId'],
        message: 'Which return is being exchanged?',
      });
    if (t.method === 'MFS' && !t.mfs)
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['mfs'],
        message: 'bKash/Nagad/Rocket transaction details are required',
      });
    if (t.method === 'CHEQUE' && !t.cheque)
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['cheque'],
        message: 'Cheque number is required',
      });
  });

export const orderDiscountSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('AMOUNT'), amountMinor: minor }).strict(),
  z.object({ kind: z.literal('PCT'), pct: z.number().min(0).max(100) }).strict(),
]);

export const posSaleSchema = z
  .object({
    /**
     * Idempotency key, generated by the till per sale. A retry after a dropped connection sends
     * the same key and gets the same sale back — never a second one.
     */
    clientRef: z.string().trim().min(8).max(64),
    /** CASH: paid in full now. CREDIT: a dealer's account takes the unpaid part. */
    paymentMode: z.enum(['CASH', 'CREDIT']).default('CASH'),
    partyId: objectId.nullable().optional(),
    walkInName: z.string().trim().max(80).nullable().optional(),
    walkInPhone: z.string().trim().max(20).nullable().optional(),
    lines: z.array(saleLineSchema).min(1, 'The cart is empty').max(200),
    orderDiscount: orderDiscountSchema.optional(),
    tenders: z.array(tenderSchema).max(6).default([]),
    /** The held sale this completes — deleted in the same transaction. */
    heldSaleId: objectId.nullable().optional(),
    note: z.string().trim().max(300).nullable().optional(),
  })
  .strict();

/** The cart a quote prices — the sale's lines, customer and discount, nothing about payment. */
export const posQuoteSchema = z
  .object({
    partyId: objectId.nullable().optional(),
    lines: z.array(saleLineSchema).min(1).max(200),
    orderDiscount: orderDiscountSchema.optional(),
  })
  .strict();

export type PosQuoteInput = z.infer<typeof posQuoteSchema>;

export type SaleLineInput = z.infer<typeof saleLineSchema>;
export type TenderInput = z.infer<typeof tenderSchema>;
export type PosSaleInput = z.infer<typeof posSaleSchema>;

// ─── Held sales ─────────────────────────────────────────────────────────────────────────

export const holdSaleSchema = z
  .object({
    label: z.string().trim().min(1, 'Name it, so it can be found again').max(40),
    partyId: objectId.nullable().optional(),
    walkInName: z.string().trim().max(80).nullable().optional(),
    lines: z.array(saleLineSchema).min(1).max(200),
    orderDiscount: orderDiscountSchema.optional(),
    note: z.string().trim().max(300).nullable().optional(),
  })
  .strict();

export type HoldSaleInput = z.infer<typeof holdSaleSchema>;

// ─── Counter returns (Day 20) ───────────────────────────────────────────────────────────

/**
 * How a counter return is settled:
 *
 *  - `CASH_REFUND` — cash back from the drawer (the Z-report nets it off);
 *  - `REPLACEMENT` — an exchange: the value becomes a credit the next sale spends as an
 *    `EXCHANGE` tender;
 *  - `CREDIT_NOTE` — a dealer's counter sale on account: the account is credited.
 */
export const COUNTER_RETURN_SETTLEMENTS = [
  'CASH_REFUND',
  'REPLACEMENT',
  'CREDIT_NOTE',
] as const;
export type CounterReturnSettlement = (typeof COUNTER_RETURN_SETTLEMENTS)[number];

export const counterReturnLineSchema = z
  .object({
    invoiceLineId: objectId,
    /** Base units — a returned dozen is 12. */
    qtyBase: z.number().int('Whole units only').min(1, 'At least 1').max(100_000),
    /** Serialised lines name exactly which units came back. */
    serials: z.array(z.string().trim().toUpperCase().min(1).max(60)).max(1000).optional(),
    /** GOOD goes back on the shelf; DAMAGED comes back in and is written off at once. */
    condition: z.enum(['GOOD', 'DAMAGED']).default('GOOD'),
  })
  .strict();

export const counterReturnSchema = z
  .object({
    /** Idempotency key, like a sale's: a retried return is not refunded twice. */
    clientRef: z.string().trim().min(8).max(64),
    invoiceId: objectId,
    reason: z.enum(RETURN_REASONS),
    settlement: z.enum(COUNTER_RETURN_SETTLEMENTS),
    lines: z.array(counterReturnLineSchema).min(1, 'Choose what is coming back').max(200),
    note: z.string().trim().max(300).nullable().optional(),
  })
  .strict();

export type CounterReturnLineInput = z.infer<typeof counterReturnLineSchema>;
export type CounterReturnInput = z.infer<typeof counterReturnSchema>;
